version: '3.9'

services:

  mongodb:
    image: mongo:latest
    platform: linux/amd64
    restart: always
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  ktor:
    build: ./server
    image: ssimyan/locdots:1.0.2
    platform: linux/amd64
    restart: always
    container_name: "locdots-server-container"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGODB_HOST: mongodb
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: locdots
      NAME: LocDots
    depends_on:
      - mongodb

  caddy:
    image: caddy:latest
    container_name: caddy-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/code/static
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ktor

networks:
  caddy:
    external: true

volumes:
  mongodb: {}
  caddy_data:
  caddy_config: