version: '3.9'

services:

  mongodb:
    image: mongo:latest
    platform: linux/amd64
    restart: always
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  locdots:
    build: ./server
    image: ssimyan/locdots:1.0.4
    platform: linux/amd64
    restart: always
    container_name: locdots-server-container
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      MONGODB_HOST: mongodb
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: locdots
      NAME: LocDots
    depends_on:
      - mongodb

volumes:
  mongodb: {}